version: "3.6"
services:
  react:
    build:
      context: ./
      dockerfile: react.Dockerfile
    ports:
      - "3000:3000"
  brownie:
    container_name: brownie_container
    build:
      context: ./
      dockerfile: brownie.Dockerfile
    ports:
      - "8545:8545"
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs_host
    ports:
      - "5001:5001"
      - "4001:4001"
      - "8080:8080"
    volumes:
    - "./ipfs_staging:/export"
    - "./ipfs_data:/data/ipfs"
#    command: |
#      ipfs config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods '["PUT", "GET", "POST", "OPTIONS"]' && \
#      ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["http://localhost:3000", "http://127.0.0.1:5001", "https://webui.ipfs.io"]' && \

